config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resource :dashboard, only: [:show]
  root 'static_pages#index'
  get 'privacy', to: 'static_pages#privacy'
  get 'team', to: 'static_pages#team'
  get 'careers', to: 'static_pages#careers'
  resources :courses, only: [:index, :show] do
    resources :enrollments, only: :create
  end
  resources :courses, only: [:index, :show]
  resources :lessons, only: [:show]
  namespace :instructor do
    resources :courses, only: [:update, :destroy, :edit] # second attempt at adding edit to courses, added entire line
    resources :lessons, only: [:update, :destroy, :edit] # second attempt at adding edit here for lessons
    resources :sections, only: [:update, :destroy, :edit] # second attempt at adding edit here for sections
    resources :sections, only: [] do
      resources :lessons, only: [:create] # first tried adding edit here for lessons
    end
    resources :courses, only: [:new, :create, :show] do # first tried adding edit, update, destroy here for courses
      resources :sections, only: [:create] #first tried adding edit here for sections
    end
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
  end
end

app/controllers/instructor/courses_controller.rb
class Instructor::CoursesController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_course, only: [:show]

  def new
    @course = Course.new
  end

  def create
    @course = current_user.courses.create(course_params)
    if @course.valid?
      redirect_to instructor_course_path(@course)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @course = Course.find(params[:id])
  end

  def update
    @course = Course.find(params[:id])
    @course.update_attributes(course_params)
    redirect_to instructor_course_path(current_course)
  end

  def destroy
    @course = Course.find(params[:id])
    @course.destroy
    redirect_to dashboard_path
  end

  def show
    @section = Section.new
    @lesson = Lesson.new
  end

  private

  def require_authorized_for_current_course
    if current_course.user != current_user
      render text: "Unauthorized", status: :unauthorized 
    end
  end

  helper_method :current_course
  def current_course
    @current_course ||= Course.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:title, :description, :cost, :image)
  end

end

app/controllers/instructor/lessons_controller.rb
class Instructor::LessonsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_section, only: [:create]
  before_action :require_authorized_for_current_lesson, only: [:update]

  def create
    @lesson = current_section.lessons.create(lesson_params)
    course = @lesson.section.course
    redirect_to instructor_course_path(course)
  end

  # begin edit addition
  def edit
    @lesson = Lesson.find(params[:id])
  end
  # end addition

  # begin destroy addition
  def destroy
    @lesson = Lesson.find(params[:id])
    course = @lesson.section.course
    @lesson.destroy
    redirect_to instructor_course_path(course)
  end

  # beginning of revised update
  def update
    @lesson = Lesson.find(params[:id])
    @lesson.update_attributes(lesson_params)
    course = @lesson.section.course
    redirect_to instructor_course_path(course)
  end
  # end of revised update - needs to redirect to instructor_course_path


# def update before I started trying to add editing funcitonality to it
  # def update
  #   current_lesson.update_attributes(lesson_params)
  #   render text: 'updated!'
  # end
  # added for editing


  private

  def require_authorized_for_current_lesson
    if current_lesson.section.course.user != current_user
      render text: 'Unauthorized', status: :unauthorized
    end
  end

  def current_lesson
    @current_lesson ||= Lesson.find(params[:id])
  end

  def require_authorized_for_current_section
    if current_section.course.user != current_user
      return render text: 'Unauthorized', status: :unauthorized
    end
  end

  helper_method :current_section
  def current_section
    @current_section ||= Section.find(params[:section_id])
  end

  def lesson_params
    params.require(:lesson).permit(:title, :subtitle, :video, :row_order_position)
  end
end

app/controllers/instructor/sections_controller.rb
class Instructor::SectionsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_course, only: [:create]
  before_action :require_authorized_for_current_section, only: [:update]

  def create
    @section = current_course.sections.create(section_params)
    redirect_to instructor_course_path(current_course)
  end

  def edit
    @section = Section.find(params[:id])
  end

  def update
    @section = Section.find(params[:id])
    @section.update_attributes(section_params)
    redirect_to instructor_course_path(current_course)
  end

  def destroy
    @section = current_section
    @section.destroy
    course = @section.course
    redirect_to instructor_course_path(course)
  end

  private

  def require_authorized_for_current_section
    if current_section.course.user != current_user
      render text: 'Unauthorized', status: :unauthorized
    end
  end

  def current_section
    @current_section ||= Section.find(params[:id])
  end

  def require_authorized_for_current_course
    if current_course.user != current_user
      render text: "Unauthorized", status: :unauthoried
    end
  end

  helper_method :current_course
  def current_course
    if params[:course_id]
      @current_course ||= Course.find(params[:course_id])
    else
      current_section.course
    end
  end

  def section_params
    params.require(:section).permit(:title, :row_order_position)
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/instructor/courses_helper.rb
module Instructor::CoursesHelper
end

app/helpers/instructor/lessons_helper.rb
module Instructor::LessonsHelper
end

app/helpers/instructor/sections_helper.rb
module Instructor::SectionsHelper
end

app/views/instructor/courses/edit.html.erb
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <%= simple_form_for @course, url: instructor_course_path(@course) do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :cost %>
    <%= f.input :image %>

    <%= f.submit "Update", class: 'btn btn-default btn-sm' %>

  <!-- begin additions for delete functionality to lessons -->
    <div class="pull-right">
      <%= link_to 'Delete Course', instructor_course_path(@course), method: :delete, data: {confirm: 'Are you sure you want to delete this?'},class: 'btn btn-danger btn-sm' %>
    </div>
  <!-- end additions for deleting functionality to lessons -->
  <% end %>
</div>

app/views/instructor/courses/new.html.erb
<br />
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1>Add a new course</h1>
  <%= simple_form_for @course, url: instructor_courses_path do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :cost %>
    <%= f.input :image %>
    <br />
    <%= f.submit "Create", class: 'btn btn-primary' %>
    <br />
  <% end %>
  <br />
</div>

app/views/instructor/courses/show.html.erb
<script>
  $(function() {
    $('.new-lesson-button').click(function() {
      var lessonUrl = $(event.target).data('lesson-url');
      $('#newLessonForm').attr('action', lessonUrl);
    });
    $('.lessons').sortable({
      update: function( event, ui) {
        $.ajax({
          type: 'PUT',
          url: ui.item.data('update-url'),
          dataType: 'json',
          data: { lesson: { row_order_position: ui.item.index() } }
        });
      }
    });
    $('.sections').sortable({
      update: function( event, ui ) {
        $.ajax({
          type: 'PUT',
          url: ui.item.data('update-url'),
          dataType: 'json',
          data: { section: { row_order_position: ui.item.index() } }
        });
      }
    });
  });
</script>

<br />
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1 class="text-center"><%= current_course.title %></h1>
  <%= image_tag current_course.image, class: 'img-responsive' %>
  
  <br />
  <%= link_to 'Preview As Student...', course_path(current_course), class: 'btn btn-warning pull-right' %>
  <br class="clr" />

  <div class="text-center">
    <!-- Button trigger modal -->
    <button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#newSectionModal">
      New Section...
    </button>
    <!-- Begin changes for course editing functionality -->
    <%= link_to 'Edit Course', edit_instructor_course_path(current_course), class: 'btn btn-info btn-lg' %>
    <!-- End changes for course editing functionality -->


  </div>

  <ul class="sections">
    <% current_course.sections.rank(:row_order).each do |section| %>
      <li data-update-url="<%= instructor_section_path(section) %>" class="section-li">
        <div class="header pull-left">
          <span class="glyphicon glyphicon-list"></span>
            <%= section.title %>
        </div>
        <!-- Button trigger modal -->
        <button class="btn btn-primary btn-sm pull-right new-lesson-button" data-toggle="modal" data-target="#newLessonModal" data-lesson-url="<%= instructor_section_lessons_path(section) %>">
          New Lesson...
        </button>

        <br class="clr" />
        <br class="clr" />

        <ul class="lessons">
          <% section.lessons.rank(:row_order).each do |lesson| %>
            <li data-update-url="<%= instructor_lesson_path(lesson) %>">
            <div class="col-xs-1">
              <br />
              <span class="glyphicon glyphicon-list"></span>
            </div>
            <div class="col-xs-11 text-center>">
              <p>
                <b><%= lesson.title %></b>
              </p>
              <p>
                <%= lesson.subtitle %>
              </p>
              <!-- Begin changes for lesson editing functionality -->
              <div class="pull-right">
                <%= link_to 'Edit Lesson', edit_instructor_lesson_path(lesson), class: 'btn btn-info btn-sm' %>
              </div>
              <!-- End changes for lesson editing functionality -->
            </div>
            <br class="clr" />
            </li>
          <% end %>
          <!-- Begin changes for secion editing functionality -->
          <div class="pull-right">
            <%= link_to 'Edit Section', edit_instructor_section_path(section), class: 'btn btn-info btn-sm' %>
          </div>
          <!-- End changes for section editing functionality -->
        </ul>
        <br class="clr" />
      </li>
    <% end %>
  </ul>

</div>



<!-- Modal -->
<div class="modal fade" id="newSectionModal" tabindex="-1" role="dialog" aria-labelledby="newSectionModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="newSectionModalLabel">Add a new section</h4>
      </div>
      <%= simple_form_for @section, url: instructor_course_sections_path(current_course) do |f| %>
        <div class="modal-body">
          <%= f.input :title %>
        </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= f.submit "Add a section", class: 'btn btn-primary' %>
      </div>
      <% end %>
    </div>
  </div>
</div>




<!-- Modal -->
<div class="modal fade" id="newLessonModal" tabindex="-1" role="dialog" aria-labelledby="newLessonModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="newLessonModalLabel">Add a new lesson</h4>
      </div>
      <%= simple_form_for @lesson, url: "#", html: {id: 'newLessonForm' } do |f| %>
        <div class="modal-body">
            <%= f.input :title %>
            <%= f.input :subtitle %>
            <%= f.input :video %>
         
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= f.submit "Add the lesson", class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>